### ISSUE TITLE
Private key & host details

### ISSUE THREAD

**Issue by Nexact** [maximumstock/poe-stash-indexer#166]
Hello,

I've found the following private key & host detail in that [file](https://github.com/maximumstock/poe-stash-indexer/blob/8fc215b91f6995cdd3f68606e9077dc121028033/docs/restart.sh)

I believe it doesn't belong there. 

Nice project !

**Comment by maximumstock** [comment]
Oh wow, I'm so embarrased...

Thank you very much for reaching out and pointing this out to me! I rotated the passwords and keys, so it should be fine now.

May I send you some pizza/beer money via PayPal or sth?

**Comment by Nexact** [comment]
No problem hehe ;) I was just looking at your code and the way you've built everything - you did a great job. 

I was thinking about using it to build some ML stuff around it so I can scan my stash and identity items that has a potential value higher than a certain threshold. 

Curiously, what are you planning to do with the project ?

**Comment by maximumstock** [comment]
Well, thank you again then! :)

> I was thinking about using it to build some ML stuff around it so I can scan my stash and identity items that has a potential value higher than a certain threshold.

Thats certainly a cool idea! From what I've heard its really hard to dynamically price items. The only tool that still exists that does this is [poeprices.info](https://www.poeprices.info/) AFAIK. But you'll certainly have a lot of people interested if you come up with something yourself!

> Curiously, what are you planning to do with the project ?

There is sadly no short answer, so I'll just give you what comes to my mind.

IIRC, I built the `indexer` crate to have my own data collection infrastructure for the public stash tab API. Based on that collected data, I wanted to build a dataset (with the code located in the `stash-differ` crate) to track the changes of all stashes of players in between stash tab API updates. [This work-in-progress README](https://github.com/maximumstock/poe-stash-indexer/blob/master/docs/problem.md#comparing-raw-stashrecord-snapshots) (that I just noticed also got commited when I accidentally added the shell script you reported) roughly sketches a few thoughts around this.

The ultimate goal was to have a dataset with all the changes a player produces in their stashes throughout some time window and to use that dataset to cluster the playerbase into subgroups to identify price fixes, ie. players that willingly price items too cheaply in order to deceive other players in their item price research to manipulate the market and make other players misprice their items too cheap as well, so the price fixers can buy them off under actual market value.

I never got around to do any actual useful EDA/analysis of said change-tracking dataset. There is one big fundamental flaw which is that you never know if any item actually got sold. This makes many very interesting applications of the public stash tab API impossible because your inference of what happened is easily gamed by anyone or simply very error prone at the least.

So I just moved to building less complicated services around the stash tab API data, like the `trade-ingest` & `trade-api` services and added things that I learned at work, like tracing, etc., to gain some operational experience.

The next idea was to have a service that tracks your stashes and lets you setup a notification when you farmed a certain number of Chaos recipe sets. But I don't think it would be very useful, so its on hold for now.

That is sort of whats going on so far. Feel free to build on top or suggest ideas if you have any you want to share!
