### ISSUE TITLE
Advice on the item indexing

### ISSUE THREAD

**Issue by arturino009** [maximumstock/poe-stash-indexer#220]
Hi @maximumstock
Your API implementation looks very useful and interesting. 
Honestly, I'm here just to ask some advice, as you seem pretty knowledgable about this.
I myself made an economy indexing tool https://github.com/arturino009/POEcluster , which searches the market for different cluster jewel combinations, to determine the combinations that are worth crafting. The problem that I'm facing is the official trade request limit, so I can make only 1 request every 10 seconds (and there are a lot of combinations).
I was wondering maybe your tool can help somehow, since you are indexing everything anyway? Im not too sure, since it looks like you are only offering request for bulk currency.
I've never worked with the public stash stream, so I have no clue how it works. As I understand, its impossible to request a specific type of items from the official stream (only clusters for example), and nothing is sorted anyway. I have no idea how big the dataset would be anyway, so it might be impossibly big for a regular user.

So I'm asking for some advice. What could I even possibly do to improve the speed of my tool, while also not downloading terrabytes of data for anyone who is using it? I don't care about market age really, I just need a general overview of cluster combination economy

**Comment by maximumstock** [comment]
Hey @arturino009, sorry for my late answer.

> I myself made an economy indexing tool https://github.com/arturino009/POEcluster , which searches the market for different cluster jewel combinations, to determine the combinations that are worth crafting. The problem that I'm facing is the official trade request limit, so I can make only 1 request every 10 seconds (and there are a lot of combinations).

I had the same problem which caused me to start this project :).

> I was wondering maybe your tool can help somehow, since you are indexing everything anyway? Im not too sure, since it looks like you are only offering request for bulk currency.
I've never worked with the public stash stream, so I have no clue how it works. As I understand, its impossible to request a specific type of items from the official stream (only clusters for example), and nothing is sorted anyway. I have no idea how big the dataset would be anyway, so it might be impossibly big for a regular user.

Alright I had to do some digging as I haven't touched the code & deployment in a while. While I'm advertising that `trade.maximumstock.net` only supports bulk currency items, it actually supports all item names. You can actually search for
```
POST http://trade.maximumstock.net/trade
content-type: application/json

{
    "sell": "Dangerous Large Cluster Jewel of the Drake"
}
```

and receive

```
HTTP/1.1 200 OK
Server: nginx/1.20.2
Date: Sat, 22 Oct 2022 21:44:57 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Content-Encoding: gzip

{
  "count": 2,
  "offers": [
    {
      "item_id": "db66383d7a189e453b2746345532a9bbeca34de800b70378ff23ac320bbddc60",
      "stash_id": "b5467092cf2e1f4313b7288c98e07b9238c37521341dc5ebb9b5ae5df62b738b",
      "sell": "Dangerous Large Cluster Jewel of the Drake",
      "buy": "Divine Orb",
      "seller_account": "pznmslz",
      "stock": 1,
      "conversion_rate": 1.0,
      "created_at": "2022-10-09T05:35:40"
    },
    {
      "item_id": "214877ac7a808680c9e9f626b8a139cb85e859dfd715b9d75eab7f331fc9f925",
      "stash_id": "1e99e062fd41b2c1e880ce4aa961dc116ec0351d7a1b8f431e44462fddacda56",
      "sell": "Dangerous Large Cluster Jewel of the Drake",
      "buy": "Chaos Orb",
      "seller_account": "aaa6868",
      "stock": 1,
      "conversion_rate": 66.0,
      "created_at": "2022-10-07T19:49:19"
    }
  ]
}
```
PS: The data seems to be inconsistent because my service was down, thats why the `created_at` timestamp is from early October. I'll need to look into this regardless.

So apparently, I was too lazy to actually filter for bulk currency items, lol. So if I understand your Cluster Jewel use-case correctly, you would need to make one request for each jewel combination of `<prefix> x <small | medium | large> x <suffix>` to get all listings at a given time. This is obviously very inefficient. You could get away with it if you run some webservice yourself that queries my API in the background and regularly requests new data, but having each client query this data separately is inefficient and probably too slow too.

Another approach - probably the one I would use if I want to provide your tool as a service - is to have some kind of indexer that listens to the public stash tab API (doesn't have to be my `indexer` project, could also be something like [this](https://www.reddit.com/r/pathofexiledev/comments/q8yyqw/searching_trade_beyond_10_items_or_how_difficult/hhlrou8/?context=3)) and processes and transforms the stream into the data format you need, ie. filters for jewel data, maybe preserves the item affixes, etc., and then you'd have some webservice that queries that data from a database.

Another approach to speed up your tool - if you want to stick to your client-based Python tool - is to allow your users to add their personal `POE_SESSION_ID` so that their rate limit on `pathofexile.com/trade` is increased. I'm not sure what the terms and conditions on that is, but you should find more information on it online.

**Comment by arturino009** [comment]
It seems there is no easy way for this, so I'll try to read the stash river myself. The link you gave me is very helpful.
Sadly poe.trade will be shut down tommorow, so that won't be helpful.
Thanks for the response!
